### ISSUE TITLE
Set up local database for testing

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket#74]

**Comment by bfbachmann** [comment]
@bobheadxi It might be better to just mock out the DB. That way we don't have to worry about setting up and tearing down tables before/after all our tests. It also makes the test setup and Travis config easier.

**Comment by bobheadxi** [comment]
Depends - it might be a good idea, especially given last night's brief confusion over the `SetIsAdmin` functionality. I've done a similar Postgres test setup before and it's pretty painless, and Inertia has a setup that allows integration tests to be skipped via a `--short` flag:

```go
func TestBootstrapIntegration(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test")
	}
        // ...
```
